development:
  adapter: async
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4296a8da7ccb337d3098441192a6151e@soldierfish.redistogo.com:10411/
  channel_prefix: chatter_production
